version: '3.8'
services:
  adminer:
    image: adminer
    container_name: adminer-v-insight
    environment:
      ADMINER_DESIGN: pepa-linha
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
  database:
    image: postgres
    container_name: postgres-v-insight
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: v-insight
